CREATE TABLE Albums (
    AlbumId INT PRIMARY KEY IDENTITY(1,1),
    Nom NVARCHAR(100) NOT NULL,
    DateCreation DATETIME NOT NULL DEFAULT GETDATE()
);

CREATE TABLE Dessins (
    DessinId INT PRIMARY KEY IDENTITY(1,1),
    AlbumId INT NOT NULL,
    Nom NVARCHAR(100) NOT NULL,
    DateCreation DATETIME NOT NULL,
    Version FLOAT NOT NULL,
    FOREIGN KEY (AlbumId) REFERENCES Albums(AlbumId) ON DELETE CASCADE
);

CREATE TABLE Figures (
    FigureId INT PRIMARY KEY IDENTITY(1,1),
    DessinId INT NOT NULL,
    TypeFigure NVARCHAR(50) NOT NULL,
    Nom NVARCHAR(100) NOT NULL,
    X INT NOT NULL,
    Y INT NOT NULL,
    CouleurR TINYINT NOT NULL,
    CouleurG TINYINT NOT NULL,
    CouleurB TINYINT NOT NULL,
    X2 INT NULL,
    Y2 INT NULL,
    Rayon INT NULL,
    FOREIGN KEY (DessinId) REFERENCES Dessins(DessinId) ON DELETE CASCADE
);
